# Generated by Django 5.0.1 on 2024-01-24 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='antecedentes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cirugias_previas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='derivada_por',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='examen_fisico',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hijos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='mac',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pareja',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sintomas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.CharField(blank=True, max_length=200)),
                ('comentario_consulta', models.TextField()),
                ('fecha_um', models.CharField(blank=True, max_length=30)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
