# Generated by Django 5.0.1 on 2024-01-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_antecedentes_paciente_cirugias_previas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
