# Generated by Django 5.0.1 on 2024-01-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_historiaclinica_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='fecha_um',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='antecedentes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='hijos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='mac',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='pareja',
        ),
    ]
