# Generated by Django 5.0.1 on 2024-02-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_historiaclinica_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='cirugias_previas',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='examen_fisico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='examen_fisico',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='sintomas',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
