# Generated by Django 5.0.1 on 2024-02-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_remove_paciente_cirugias_previas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
