# Generated by Django 5.0.1 on 2024-02-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_paciente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='examen_fisico',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='motivo_consulta',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sintomas',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
