# Generated by Django 5.0.1 on 2024-02-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_alter_historiaclinica_examen_fisico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenHistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='historias_clinicas/')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.historiaclinica')),
            ],
        ),
    ]
